# Generated by Django 6.0.1 on 2026-01-31 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='보호소명')),
                ('address', models.CharField(max_length=255, verbose_name='주소')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('description', models.TextField(verbose_name='보호소 소개')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shelters/')),
                ('feed_support_url', models.URLField(blank=True, verbose_name='사료후원 링크')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='봉사 날짜')),
                ('max_participants', models.IntegerField(default=5, verbose_name='모집 인원')),
                ('current_participants', models.IntegerField(default=0, verbose_name='현재 신청 인원')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='shelter.shelter')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('대기', '대기'), ('승인', '승인'), ('취소', '취소')], default='대기', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.volunteerschedule')),
            ],
        ),
    ]
