# Generated by Django 6.0.1 on 2026-02-12 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='사료명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('image', models.ImageField(upload_to='products/', verbose_name='사료이미지')),
                ('description', models.TextField(verbose_name='사료설명')),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='user',
        ),
        migrations.RemoveField(
            model_name='volunteerschedule',
            name='shelter',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='feed_support_url',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='phone',
        ),
        migrations.AlterField(
            model_name='shelter',
            name='address',
            field=models.CharField(max_length=200, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='description',
            field=models.TextField(verbose_name='보호소소개'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='image',
            field=models.ImageField(default='', upload_to='shelters/', verbose_name='보호소이미지'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='수량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='후원시간')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.shelter', verbose_name='보호소')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='후원자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.product', verbose_name='후원물품')),
            ],
        ),
        migrations.AddField(
            model_name='shelter',
            name='target_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelter.product', verbose_name='필요사료'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='VolunteerApplication',
        ),
        migrations.DeleteModel(
            name='VolunteerSchedule',
        ),
    ]
