# Generated by Django 6.0.1 on 2026-02-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_shelter_region_shelter_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='region',
            field=models.CharField(choices=[('서울', '서울'), ('부산', '부산'), ('대구', '대구'), ('인천', '인천'), ('광주', '광주'), ('대전', '대전'), ('울산', '울산'), ('세종', '세종'), ('경기', '경기'), ('강원', '강원'), ('충북', '충북'), ('충남', '충남'), ('전북', '전북'), ('전남', '전남'), ('경북', '경북'), ('경남', '경남'), ('제주', '제주')], default='서울', max_length=20, verbose_name='지역'),
        ),
    ]
