# Generated by Django 6.0.1 on 2026-02-13 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0006_donation_imp_uid_merchant_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-created_at']},
        ),
    ]
