"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env 파일 로드 (선택, pip install python-dotenv)
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECRET_KEY: 프로덕션에서는 반드시 환경변수 DJANGO_SECRET_KEY 로만 주입 (저장소에 하드코딩 금지)
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-q4wjy)7(i&%wl14f-kd%ui%@&(x$=pl+*819epu5z9t&im*ni9',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS',
    'DAEWONKIM.pythonanywhere.com,127.0.0.1,localhost',
).split(',')
ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'board',
    'shelter',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 이 부분이 핵심입니다! 
        # 프로젝트 루트의 templates 폴더를 탐색 경로에 추가합니다.
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 업로드 파일 (보호소/사료 이미지)
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 이메일 (비밀번호 재설정, 아이디 찾기 - 개발 환경에서는 콘솔로 출력)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'no-reply@foritpet.local'

# 로그인/로그아웃 (보안: 인증 실패 시 이 URL로 리다이렉트)
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# ---------------------------------------------------------------------------
# 세션·쿠키 보안
# ---------------------------------------------------------------------------
# 브라우저(탭)를 모두 닫으면 세션 쿠키가 만료되도록 (재방문 시 로그인 필요)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# 최대 유지 시간(초). 활동 시마다 연장하려면 SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = int(os.environ.get('SESSION_COOKIE_AGE', '3600'))  # 기본 1시간
SESSION_SAVE_EVERY_REQUEST = True  # 요청마다 만료 시각 갱신(슬라이딩, 활동 중에는 유지)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
# HTTPS 사용 시 아래 프로덕션 블록에서 SESSION_COOKIE_SECURE = True 로 설정

# CSRF: HttpOnly=False 권장 — 일부 AJAX/스크립트에서 토큰 접근 필요할 수 있음
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if o.strip()
]

# ---------------------------------------------------------------------------
# 업로드·요청 크기 제한 (DoS 완화)
# ---------------------------------------------------------------------------
DATA_UPLOAD_MAX_MEMORY_SIZE = 2_621_440  # 2.5MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 2_621_440

# ---------------------------------------------------------------------------
# HTTPS/프로덕션 전용 (DEBUG=False 이고 DJANGO_USE_HTTPS=1 일 때만)
# 로컬에서 DEBUG=False + HTTP 테스트 시: DJANGO_USE_HTTPS=0
# ---------------------------------------------------------------------------
DJANGO_USE_HTTPS = os.environ.get('DJANGO_USE_HTTPS', '1' if not DEBUG else '0') == '1'
if not DEBUG and DJANGO_USE_HTTPS:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'

# 개발(DEBUG)에서도 기본 보안 헤더
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# 포트원(아임포트) — 비밀키는 환경변수로만 설정 (코드에 실제 키를 넣지 마세요)
PORTONE_IMP_CODE = os.environ.get('PORTONE_IMP_CODE', 'imp88875057')
PORTONE_REST_API_KEY = os.environ.get('PORTONE_REST_API_KEY', '')
PORTONE_REST_API_SECRET = os.environ.get('PORTONE_REST_API_SECRET', '')
